version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  postgres_data: