name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10
        options: --privileged
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io

    - name: Build Docker image
      run: |
        docker build -t fastapi-web .
    
    - name: Run Docker Compose
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" > .env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
        echo "TOKEN_VERIFICATION_KEY=${{ secrets.TOKEN_VERIFICATION_KEY }}" >> .env
        docker-compose up -d

    - name: Run tests
      run: |
        docker-compose exec web poetry run pytest

    - name: Shut down Docker Compose
      if: always()
      run: |
        docker-compose down
